apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-admin
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    repoURL: https://github.com/bradfordwagner/chart-namespaces.git
    targetRevision: 2.0.1
    path: .
    helm:
      releaseName: namespaces
      parameters:
        - name: namespaces
          value: argocd|vault
  destination:
    name: in-cluster
  project: default
  syncPolicy:
    automated:
      prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces-cicd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  source:
    repoURL: https://github.com/bradfordwagner/chart-namespaces.git
    targetRevision: 2.0.1
    path: .
    helm:
      releaseName: namespaces
      parameters:
        - name: namespaces
          value: argo|argo-events
  destination:
    name: cicd
  project: default
  syncPolicy:
    automated:
      prune: true
