apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-namespaces
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - cluster: admin
            namespaces: >
              argo-workflows
              argocd
              vault
          - cluster: cicd
            namespaces: >
              argo
              argo-events
              argo-workflows
              workflows
  template:
    metadata:
      name: namespaces-{{ cluster }}
      annotations:
        argocd.argoproj.io/sync-wave: "0"
    spec:
      source:
        repoURL: https://github.com/bradfordwagner/chart-namespaces.git
        targetRevision: 2.1.0
        path: .
        helm:
          releaseName: namespaces
          parameters:
            - name: namespaces
              value: '{{ namespaces }}'
      destination:
        name: '{{ cluster }}'
      project: default
      syncPolicy:
        automated:
          prune: true
