apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bradfordwagner-events-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # create only after tier 1 dependencies have been injected - argo-events
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/bradfordwagner/argo-events-webhook.git
    targetRevision: 1.21.0
    path: .
    helm:
      releaseName: events-webhook
  destination:
    name: cicd
    namespace: argo-events
  project: default
  syncPolicy:
    automated:
      prune: true

