# used to initialize cluster contexts - from secret
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/bradfordwagner/deploy-chart-vault.git
    targetRevision: HEAD
    path: .
    helm:
      releaseName: vault
  destination:
    name: in-cluster
    namespace: vault
  project: default
  syncPolicy:
    automated:
      prune: true
