# used to initialize cluster contexts - from secret
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - list:
      elements:
      - cluster: admin
        externalVaultAddr: "" # sets injection to local cluster
      - cluster: cicd
        externalVaultAddr: "http://bradfordwagner.com:8200"
  template:
    metadata:
      name: '{{cluster}}-vault'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
      source:
        # repoURL: https://github.com/bradfordwagner/deploy-chart-vault.git
        repoURL: bradfordwagner0.azurecr.io/helm
        chart: bradfordwagner-deploy-vault
        targetRevision: 1.1.0
        path: .
        helm:
          parameters:
            - name: vault.injector.externalVaultAddr
              value: '{{externalVaultAddr}}'
            - name: vault.injector.authPath
              value: 'auth/kubernetes/{{cluster}}'
            - name: vault.csi.extraArgs[0]
              value: '-vault-addr=http://bradfordwagner.com:8200'
            - name: vault.csi.extraArgs[1]
              value: '-vault-tls-skip-verify=true'
            - name: vault.csi.extraArgs[2]
              value: '-vault-mount=kubernetes/{{cluster}}'
          releaseName: vault
      destination:
        name: '{{cluster}}'
        namespace: vault
