# used to initialize cluster contexts - from secret
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
  - list:
      elements:
      - cluster: admin
        externalVaultAddr: "" # sets injection to local cluster
  template:
    metadata:
      name: '{{cluster}}-vault'
      annotations:
        argocd.argoproj.io/sync-wave: "1"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
      source:
        repoURL: https://github.com/bradfordwagner/deploy-chart-vault.git
        targetRevision: 2.0.0
        path: .
        helm:
          parameters:
            - name: vault.injector.externalVaultAddr
              value: '{{externalVaultAddr}}'
            - name: vault.injector.authPath
              value: 'auth/kubernetes/{{cluster}}'
          releaseName: vault
      destination:
        name: '{{cluster}}'
        namespace: vault
      ignoreDifferences:
      - group: admissionregistration.k8s.io
        kind: MutatingWebhookConfiguration
        jsonPointers:
        - /webhooks/0/clientConfig/caBundle
