# used to initialize cluster contexts - from secret
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-k8s-auth
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  generators:
  - list:
      elements:
      - cluster: admin
      - cluster: cicd
  template:
    metadata:
      name: '{{cluster}}-vault-k8s-auth'
      annotations:
        argocd.argoproj.io/sync-wave: "2"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      syncPolicy:
        automated:
          prune: true
      source:
        # repoURL: https://github.com/bradfordwagner/chart-vault-k8s-auth.git
        repoURL: bradfordwagner0.azurecr.io/helm
        chart: bradfordwagner-vault-k8s-auth
        targetRevision: 1.2.0
        path: .
        helm:
          releaseName: vault
      destination:
        name: '{{cluster}}'
        namespace: vault
