apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/bradfordwagner/deploy-argoworkflow.git
    targetRevision: feature/pin-version
#   targetRevision: HEAD
    path: .
  destination:
    name: cicd
  project: default
  syncPolicy:
    automated:
      prune: true
