apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5" # create only after tier 1 dependencies have been injected - argooworkflows
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/bradfordwagner/chart-docker-kubernetes-driver
    targetRevision: 1.0.1
    path: .
    helm:
      releaseName: docker-driver
  destination:
    name: cicd
    namespace: docker-driver
  project: default
  syncPolicy:
    automated:
      prune: true

